import { useEffect, useState } from 'react'
import { quizQuestions } from '../data/dummyData'
import { getStorage, setStorage, storageKeys } from '../utils/localStorage'

export default function Kuis() {
  const [name, setName] = useState(''); const [answers, setAnswers] = useState({}); const [sec, setSec] = useState(300)
  const [history, setHistory] = useState(getStorage(storageKeys.quizResults, [])); const [last, setLast] = useState(null)
  useEffect(() => { const t = setInterval(() => setSec((s) => Math.max(0, s - 1)), 1000); return () => clearInterval(t) }, [])
  const submit = (e) => { e.preventDefault(); if (!name || Object.keys(answers).length < quizQuestions.length) return alert('Data gagal jika input kosong'); const correct = quizQuestions.filter((q) => answers[q.id] === q.answer).length; const score = Math.round(correct / quizQuestions.length * 100); const rec = { id: crypto.randomUUID(), studentName: name, score, correct, total: quizQuestions.length, status: score >= 70 ? 'Lulus' : 'Tidak Lulus', submittedAt: new Date().toISOString() }; const n = [rec, ...history]; setHistory(n); setStorage(storageKeys.quizResults, n); setLast(rec); alert('Data berhasil disimpan') }
  return <div className='stack'><h2>Kuis / Ujian</h2><section className='grid cols-4'>{[['Jumlah soal', quizQuestions.length], ['Durasi', '5 menit'], ['Passing grade', '70'], ['Status', 'Aktif']].map(([t, v]) => <article className='card' key={t}><p>{t}</p><h3>{v}</h3></article>)}</section><form className='card form' onSubmit={submit}><div className='sticky'>Timer: {Math.floor(sec / 60)}:{String(sec % 60).padStart(2, '0')}</div><input placeholder='Nama peserta' value={name} onChange={(e) => setName(e.target.value)} />{quizQuestions.map((q) => <article className='card' key={q.id}><p>{q.id}. {q.q}</p>{q.options.map((o, i) => <label key={o} className='block'><input type='radio' name={`q${q.id}`} onChange={() => setAnswers({ ...answers, [q.id]: i })} /> {o}</label>)}</article>)}<button className='btn'>Submit Kuis</button></form>{last && <section className='card'><h3>Score: {last.score}</h3><p>Status: {last.status} • Benar {last.correct}/{last.total}</p><p className='notice'>Feedback: {last.score >= 70 ? 'Kompetensi dasar BLS telah memenuhi passing grade. Lanjutkan ke simulasi lanjutan.' : 'Pelajari kembali materi Dangerous, AVPU, Circulation, dan Breathing sebelum mengulang kuis.'}</p></section>}<div className='table-wrap'><table><tbody>{history.map((h) => <tr key={h.id}><td>{h.studentName}</td><td>{h.score}</td><td>{h.status}</td></tr>)}</tbody></table></div></div>
}
