import { useState } from 'react'
import { assignments } from '../data/dummyData'
import { getStorage, setStorage, storageKeys } from '../utils/localStorage'

export default function Tugas() {
  const [subs, setSubs] = useState(getStorage(storageKeys.assignmentSubmissions, []))
  const [f, setF] = useState({ assignmentId: 'A1', studentName: '', answer: '', fileName: '' })
  const submit = (e) => { e.preventDefault(); if (Object.values(f).some((v) => !v)) return alert('Data gagal jika input kosong'); const a = assignments.find((x) => x.id === f.assignmentId); const rec = { id: crypto.randomUUID(), assignmentTitle: a.title, ...f, status: 'Terkumpul', submittedAt: new Date().toISOString() }; const n = [rec, ...subs]; setSubs(n); setStorage(storageKeys.assignmentSubmissions, n); alert('Data berhasil disimpan') }
  return <div className='stack'><h2>Tugas / Assignment</h2><section className='grid cols-4'>{[['Total Tugas', assignments.length], ['Belum Dikumpulkan', Math.max(assignments.length - subs.length, 0)], ['Terkumpul', subs.length], ['Deadline Terdekat', `${assignments[0].dueInDays} hari`]].map(([t, v]) => <article className='card' key={t}><p>{t}</p><h3>{v}</h3></article>)}</section><section className='grid cols-3'>{assignments.map((a) => <article className='card' key={a.id}><h4>{a.title}</h4><p>{a.description}</p></article>)}</section><form className='card form' onSubmit={submit}><h3>Kumpulkan Jawaban</h3><select onChange={(e) => setF({ ...f, assignmentId: e.target.value })}>{assignments.map((a) => <option key={a.id} value={a.id}>{a.title}</option>)}</select><input placeholder='Nama peserta' onChange={(e) => setF({ ...f, studentName: e.target.value })} /><textarea placeholder='Jawaban' onChange={(e) => setF({ ...f, answer: e.target.value })} /><input placeholder='Nama file' onChange={(e) => setF({ ...f, fileName: e.target.value })} /><button className='btn'>Kumpulkan Jawaban</button></form><div className='table-wrap'><table><thead><tr><th>Nama</th><th>Tugas</th><th>Status</th></tr></thead><tbody>{subs.map((s) => <tr key={s.id}><td>{s.studentName}</td><td>{s.assignmentTitle}</td><td><span className='badge'>{s.status}</span></td></tr>)}</tbody></table></div></div>
}
